import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { adminApi, adminDate } from "../config/admin.js";
const labels = { totalUsers: "Users", students: "Students", teachers: "Teachers", admins: "Admins", activeUsers: "Active accounts", suspendedUsers: "Suspended accounts", totalQuizzes: "Quizzes", publishedQuizzes: "Published quizzes", groups: "Classrooms", activeGroups: "Active classrooms", archivedGroups: "Archived classrooms", assignments: "Assignments", attempts: "Attempts", submittedAttempts: "Submitted attempts", inProgressAttempts: "In-progress attempts", notifications: "Notifications", messages: "Classroom messages" };
export default function AdminDashboard() {
  const [data, setData] = useState(null), [error, setError] = useState(""), [revision, setRevision] = useState(0);
  useEffect(() => { const controller = new AbortController(); adminApi("dashboard", { signal: controller.signal }).then(result => { setData(result.dashboard); setError(""); }).catch(e => { if (e.name !== "AbortError") setError(e.message); }); return () => controller.abort(); }, [revision]);
  return <section><div className="section-row"><h2>Platform overview</h2><button className="btn btn-secondary" onClick={() => { setData(null); setError(""); setRevision(n => n + 1); }}>Refresh</button></div><p className="muted">Live database counts at refresh time. Recent activity shows up to five records per category.</p>{error && <p className="feedback feedback-error" role="alert">{error}</p>}{!data && !error && <p role="status">Loading platform metrics…</p>}{data && <><div className="stats-grid">{Object.entries(data.metrics).map(([key, value]) => <div className="stat-card" key={key}><span>{labels[key]}</span><strong>{value}</strong></div>)}</div><div className="admin-records">{Object.entries(data.recent).map(([type, rows]) => <section className="panel" key={type}><div className="section-row"><h3>Recent {type}</h3><Link className="text-link" to={`/admin/${type}`}>View all</Link></div>{rows.length ? rows.map(row => <p key={row.publicId || row.reference || row.token || row.email}><strong>{row.name || row.title}</strong><br /><span className="muted">{adminDate(row.createdAt)}</span></p>) : <p>No records yet.</p>}</section>)}</div></>}</section>;
}
