import express from "express";
import { protect, authorizeRoles } from "../middleware/authMiddleware.js";
import * as admin from "../controllers/adminController.js";
const router = express.Router();
router.use(protect, authorizeRoles("admin"));
router.get("/dashboard", admin.dashboard);
router.get("/users", admin.users);
router.get("/users/:publicId", admin.user);
router.patch("/users/:publicId/role", admin.role);
router.patch("/users/:publicId/status", admin.status);
router.get("/quizzes", admin.quizzes);
router.get("/quizzes/:reference", admin.quiz);
router.patch("/quizzes/:reference/moderation", admin.moderate);
router.get("/groups", admin.groups);
router.get("/groups/:code", admin.group);
router.patch("/groups/:code/status", admin.archive);
router.get("/assignments", admin.assignments);
router.get("/assignments/:token/analytics", admin.report);
router.get("/assignments/:token", admin.assignment);
router.get("/attempts", admin.attempts);
router.get("/attempts/:reference", admin.attempt);
export default router;
