import * as admin from "../services/adminService.js";
import { handler } from "./assignmentController.js";
const get = (name, callback) => handler(async (req, res) => res.json({ success: true, [name]: await callback(req) }));
export const dashboard = get("dashboard", req => admin.dashboard(req.user));
export const users = get("users", req => admin.users(req.user, req.query));
export const user = get("details", req => admin.userDetails(req.user, req.params.publicId));
export const role = get("user", req => admin.changeUser(req.user, req.params.publicId, "role", req.body?.role));
export const status = get("user", req => admin.changeUser(req.user, req.params.publicId, "accountStatus", req.body?.accountStatus));
export const quizzes = get("quizzes", req => admin.quizzes(req.user, req.query));
export const quiz = get("details", req => admin.quizDetails(req.user, req.params.reference));
export const moderate = get("quiz", req => admin.moderateQuiz(req.user, req.params.reference, req.body?.action));
export const groups = get("groups", req => admin.groups(req.user, req.query));
export const group = get("details", req => admin.groupDetails(req.user, req.params.code, req.query));
export const archive = get("group", req => admin.archiveGroup(req.user, req.params.code, req.body?.status));
export const assignments = get("assignments", req => admin.assignments(req.user, req.query));
export const assignment = get("assignment", req => admin.assignmentDetails(req.user, req.params.token));
export const report = get("analytics", req => admin.assignmentReport(req.user, req.params.token));
export const attempts = get("attempts", req => admin.attempts(req.user, req.query));
export const attempt = get("attempt", req => admin.attemptDetails(req.user, req.params.reference));
