import { labels, types, newQuestion, questionError } from "../config/questions.js";
function AcceptedAnswers({ value, onChange, prefix }) {
  return <fieldset className="accepted-editor"><legend>Accepted answers</legend>{value.acceptedAnswers.map((a, i) => <div className="input-action" key={i}><input aria-label={`${prefix} accepted answer ${i + 1}`} required maxLength={2000} value={a} onChange={e => onChange({ ...value, acceptedAnswers: value.acceptedAnswers.map((v, n) => n === i ? e.target.value : v) })} /><button type="button" className="btn btn-danger-soft" disabled={value.acceptedAnswers.length === 1} onClick={() => onChange({ ...value, acceptedAnswers: value.acceptedAnswers.filter((_, n) => n !== i) })}>Remove</button></div>)}<button type="button" className="btn btn-secondary" disabled={value.acceptedAnswers.length >= 50} onClick={() => onChange({ ...value, acceptedAnswers: [...value.acceptedAnswers, ""] })}>Add accepted answer</button><label className="notification-filter"><input type="checkbox" checked={!!value.caseSensitive} onChange={e => onChange({ ...value, caseSensitive: e.target.checked })} /> Case sensitive</label></fieldset>;
}
export default function QuestionEditor({ questions, onChange, timerMode }) {
  const change = (i, q) => onChange(questions.map((v, n) => n === i ? q : v));
  function move(i, direction) { const next = [...questions], target = i + direction; [next[i], next[target]] = [next[target], next[i]]; onChange(next); }
  return <div className="questions-list">{questions.map((q, i) => {
    const type = q.questionType || "singleChoice", prefix = `Question ${i + 1}`, id = q._id || q.clientKey, error = questionError(q);
    return <section className="question-card" key={id}><div className="question-card-header"><h3>{prefix}</h3><div className="assignment-actions"><button type="button" className="btn btn-secondary" disabled={!i} onClick={() => move(i, -1)}>Move up</button><button type="button" className="btn btn-secondary" disabled={i === questions.length - 1} onClick={() => move(i, 1)}>Move down</button><button type="button" className="btn btn-danger-soft" disabled={questions.length === 1} onClick={() => onChange(questions.filter((_, n) => n !== i))}>Remove question</button></div></div>
      <div className="form-group"><label htmlFor={`${id}-type`}>Question type</label><select id={`${id}-type`} value={type} onChange={e => change(i, newQuestion(e.target.value, q))}>{types.map(t => <option key={t} value={t}>{labels[t]}</option>)}</select></div>
      <div className="form-group"><label htmlFor={`${id}-prompt`}>Prompt{type === "fillBlank" ? " — use {{1}}, {{2}}, …" : ""}</label><textarea id={`${id}-prompt`} required maxLength={10000} rows={3} value={q.questionText} onChange={e => change(i, { ...q, questionText: e.target.value })} aria-describedby={error ? `${id}-error` : undefined} /></div>
      {["singleChoice", "multipleSelect"].includes(type) && <fieldset className="options-list"><legend>Options and correct answers</legend>{q.options.map((option, n) => <div className="option-row" key={n}><input type={type === "singleChoice" ? "radio" : "checkbox"} name={`${id}-correct`} aria-label={`Mark option ${n + 1} correct`} checked={type === "singleChoice" ? q.correctOption === n : q.correctOptions.includes(n)} onChange={e => change(i, type === "singleChoice" ? { ...q, correctOption: n } : { ...q, correctOptions: e.target.checked ? [...q.correctOptions, n] : q.correctOptions.filter(v => v !== n) })} /><input aria-label={`${prefix} option ${n + 1}`} required value={option} onChange={e => change(i, { ...q, options: q.options.map((v, k) => k === n ? e.target.value : v) })} /><button type="button" className="btn btn-danger-soft" disabled={q.options.length <= 2} onClick={() => change(i, { ...q, options: q.options.filter((_, k) => k !== n), ...(type === "singleChoice" ? { correctOption: q.correctOption === n ? null : q.correctOption > n ? q.correctOption - 1 : q.correctOption } : { correctOptions: q.correctOptions.filter(v => v !== n).map(v => v > n ? v - 1 : v) }) })}>Remove</button></div>)}<button type="button" className="btn btn-secondary" disabled={q.options.length >= 50} onClick={() => change(i, { ...q, options: [...q.options, ""] })}>Add option</button></fieldset>}
      {type === "trueFalse" && <div className="form-group"><label htmlFor={`${id}-boolean`}>Correct answer</label><select id={`${id}-boolean`} value={String(q.correctBoolean)} onChange={e => change(i, { ...q, correctBoolean: e.target.value === "true" })}><option value="true">True</option><option value="false">False</option></select></div>}
      {type === "shortAnswer" && <AcceptedAnswers value={q} prefix={prefix} onChange={v => change(i, v)} />}
      {type === "numeric" && <div className="form-grid">{["correctNumber", "numericTolerance"].map(f => <div className="form-group" key={f}><label htmlFor={`${id}-${f}`}>{f === "correctNumber" ? "Correct numeric value" : "Absolute tolerance (0 = exact)"}</label><input id={`${id}-${f}`} type="number" step="any" min={f === "numericTolerance" ? 0 : undefined} required value={q[f]} onChange={e => change(i, { ...q, [f]: e.target.value })} /></div>)}</div>}
      {type === "fillBlank" && <div>{q.blanks.map((b, n) => <section className="blank-editor" key={n}><h4>Blank {n + 1}: {`{{${n + 1}}}`}</h4><AcceptedAnswers value={b} prefix={`${prefix} blank ${n + 1}`} onChange={v => change(i, { ...q, blanks: q.blanks.map((x, k) => k === n ? v : x) })} /><button type="button" className="btn btn-danger-soft" disabled={q.blanks.length === 1} onClick={() => change(i, { ...q, blanks: q.blanks.filter((_, k) => k !== n) })}>Remove blank</button></section>)}<button type="button" className="btn btn-secondary" disabled={q.blanks.length >= 20} onClick={() => change(i, { ...q, blanks: [...q.blanks, { acceptedAnswers: [""], caseSensitive: false }] })}>Add blank</button><p>After removing a blank, update the prompt markers to match the new numbering.</p></div>}
      <div className="question-settings"><div className="form-group"><label htmlFor={`${id}-marks`}>Marks</label><input id={`${id}-marks`} type="number" step="any" min={1} value={q.marks} required onChange={e => change(i, { ...q, marks: Number(e.target.value) })} /></div>{timerMode === "per-question" && <div className="form-group"><label htmlFor={`${id}-time`}>Seconds</label><input id={`${id}-time`} type="number" min={5} value={q.timeLimit} required onChange={e => change(i, { ...q, timeLimit: Number(e.target.value) })} /></div>}</div>
      {error && <p id={`${id}-error`} className="feedback feedback-error">{error}</p>}
    </section>;
  })}<button type="button" className="add-question-button" onClick={() => onChange([...questions, newQuestion()])}>+ Add question</button></div>;
}
